controller:
  type: cone
  levels: [3,5,7,11,13]
  reverse: False

sections:
  cone:
    type: cone

palettes:
  rainbow_6:
    rainbow_steps: 6
  rainbow_13:
    rainbow_steps: 13
  rainbow_40:
    rainbow_steps: 40
  rainbow_256:
    rainbow_steps: 256

renderers:
  # Cone
  # -
  #   type: cone_spin
  #   section: cone
  #   palette: rainbow_40
  #   degrees_per_step: -2
  -
    type: cone_spin_full
    section: cone
    palette: rainbow_256
  # -
  #   type: cone_level
  #   section: cone
  #   palette: rainbow_6
  #   seconds_per_level: 0.3
  # -
  #   type: cone_spiral
  #   section: cone
  #   palette: rainbow_6
  #   seconds_per_level: 0.3

displays:
  -
    type: websocket
