controller:
  type: cone
  levels: [1,3,5,7,11,13]
  reverse: False

sections:
  -
    id: cone
    type: cone

palettes:
  -
    id: rainbow_6
    rainbow_steps: 6
  -
    id: rainbow_13
    rainbow_steps: 13
  -
    id: rainbow_40
    rainbow_steps: 40
  -
    id: rainbow_256
    rainbow_steps: 256

renderers:
  # Cone
  -
    type: cone_spin
    sections: cone
    palette: rainbow_40
    degrees_per_step: 2
  # -
  #   type: cone_spin_full
  #   sections: cone
  #   palette: rainbow_40
  #   degrees_per_step: 2
  # -
  #   type: cone_level
  #   sections: cone
  #   palette: rainbow_6
  #   seconds_per_level: 0.3
  # -
  #   type: cone_spiral
  #   sections: cone
  #   palette: rainbow_6
  #   seconds_per_level: 0.3

displays:
  -
    type: websocket
