controller:
  type: cone
  levels: [8, 10, 13, 15, 16, 21, 25]
  extra_leds: 12
  reverse: True
  a: 1

sections:
  cone:
    type: cone

renderer:
  type: multi_timed
  time_seconds: 10
  renderers:
    -
      type: cone_spin_full
      section: cone
      palette: rainbow_40
    -
      type: multi_all
      renderers:
        -
          type: cone_spin_line
          section: cone
          palette: rainbow_256
        -
          type: cone_spin_line
          section: cone
          palette: rainbow_256
          start_degrees: 120
        -
          type: cone_spin_line
          section: cone
          palette: rainbow_256
          start_degrees: 240
    -
      type: cone_spiral_fill
      section: cone
      palette: rainbow_107
      reverse: True
    -
      type: cone_spiral_drip
      section: cone
      palette: rainbow_107
      reverse_colour: True
    -
      type: cone_level
      section: cone
      palette: rainbow_40

displays:
  - type: websocket
