controller:
  type: cone
  levels: [8, 10, 12, 16, 15, 21, 25, 30]

  reverse: True

sections:
  cone:
    type: cone

palettes:
  rainbow_6:
    rainbow_steps: 6
  rainbow_13:
    rainbow_steps: 13
  rainbow_40:
    rainbow_steps: 40
  rainbow_256:
    rainbow_steps: 256

renderer:
  type: multi_timed
  time_seconds: 2
  renderers:
    -
      type: cone_spin_full
      section: cone
      palette: rainbow_256
    -
      type: multi_all
      renderers:
        -
          type: cone_spin_line
          section: cone
          palette: rainbow_40
          degrees_per_step: -2
        -
          type: cone_spin_line
          section: cone
          palette: rainbow_40
          degrees_per_step: -2
          start_degrees: 120
        -
          type: cone_spin_line
          section: cone
          palette: rainbow_40
          degrees_per_step: -2
          start_degrees: 240
    # -
    #   type: cone_level
    #   section: cone
    #   palette: rainbow_6
    #   seconds_per_level: 0.3
    # -
    #   type: cone_spiral
    #   section: cone
    #   palette: rainbow_6
    #   seconds_per_level: 0.3

displays:
  -
    type: websocket
