controller:
  type: rectangular
  width: 60
  height: 2
  reverse_x: True
  reverse_y: False

sections:
  top:
    type: rectangular
    x: 0
    y: 0
    width: 60
    height: 1
  bottom:
    type: rectangular
    x: 0
    y: 1
    width: 60
    height: 1
    reverse_x: True

palettes:
  rainbow_60:
    rainbow_steps: 60

renderer:
  type: multi_all
  renderers:
    -
      type: rainbow
      section: top
      palette: rainbow_60
    -
      type: rainbow
      section: bottom
      palette: rainbow_60

displays:
  -
    type: websocket
