controller:
  width: 60
  height: 2
  reverse_x: True
  reverse_y: False

sections:
  top_left:
    x: 0
    y: 0
    width: 30
    height: 1
  top_right:
    x: 30
    y: 0
    width: 30
    height: 1
  bottom:
    x: 0
    y: 1
    width: 60
    height: 1
  patch1:
    x: 5
    y: 0
    width: 5
    height: 2
  patch2:
    x: 15
    y: 0
    width: 5
    height: 2

renderers:
  # Rainbows
  -
    type: rainbow
    sections: top_left
  -
    type: rainbow
    sections: top_right
    train_length: 30
  -
    type: rainbow
    sections: bottom

  # Patches
  -
    type: patch
    sections: patch1
    colours:
      - [255, 0, 0]
  -
    type: patch
    sections: patch2
    rainbow_steps: 250

  # Clock
  # -
  #   type: clock
  #   sections: bottom

  # Gravity shots
  # -
  #   type: gravity_shot
  #   sections: bottom

  # Gravity Drips

displays:
  -
    type: websocket
