controller:
  width: 60
  height: 2
  reverse_x: True
  reverse_y: False

sections:
  -
    id: top_left
    x: 0
    y: 0
    width: 30
    height: 1
  -
    id: top_right
    x: 30
    y: 0
    width: 30
    height: 1
  -
    id: bottom
    x: 0
    y: 1
    width: 60
    height: 1
  -
    id: patch1
    x: 5
    y: 0
    width: 5
    height: 2
  -
    id: patch2
    x: 15
    y: 0
    width: 5
    height: 2

palettes:
  -
    id: red_fade
    colour: red
    fade_steps: 10
    fade_hold: 10
  -
    id: rgb
    colours: [red, green, blue]
  -
    id: rgb_fade
    colours: [red, green, blue]
    fade_steps: 10
    fade_hold: 10
  -
    id: rainbow_fade
    rainbow_steps: 10
    fade_steps: 10
    fade_hold_on: 20
    fade_hold_off: 10

  -
    id: rainbow_10
    rainbow_steps: 10
  -
    id: rainbow_30
    rainbow_steps: 30
  -
    id: rainbow_250
    rainbow_steps: 250

renderers:
  # Rainbows
  -
    type: rainbow
    sections: top_left
    palette: rainbow_10
  -
    type: rainbow
    sections: top_right
    palette: rainbow_30
  -
    type: rainbow
    sections: bottom
    palette: rainbow_10

  # Patches
  -
    type: patch
    sections: patch1
    palette: red
  -
    type: patch
    sections: patch2
    palette: rainbow_250

  # Clock
  -
    type: clock
    sections: bottom

  # Gravity shots
  -
    type: gravity_shot
    sections: bottom

  # Gravity Drips
  -
    type: gravity_drip
    sections: bottom

displays:
  -
    type: websocket
