controller:
  type: rectangular
  width: 60
  height: 2
  reverse_x: True
  reverse_y: False

sections:
  top_left:
    type: rectangular
    x: 0
    y: 0
    width: 30
    height: 1
  top_right:
    type: rectangular
    x: 30
    y: 0
    width: 30
    height: 1
  bottom:
    type: rectangular
    x: 0
    y: 1
    width: 60
    height: 1
  patch1:
    type: rectangular
    x: 5
    y: 0
    width: 5
    height: 2
  patch2:
    type: rectangular
    x: 15
    y: 0
    width: 5
    height: 2

palettes:
  red_fade:
    colour: red
    fade_steps_in: 10
    fade_steps_out: 10
    fade_hold_on: 10
    fade_hold_off: 10
  rgb:
    colours: [red, green, blue]
  rgb_fade:
    colours: [red, green, blue]
    fade_steps_in: 10
    fade_steps_out: 10
    fade_hold_on: 10
    fade_hold_off: 10
  rainbow_fade:
    rainbow_steps: 10
    fade_steps_in: 10
    fade_steps_out: 10
    fade_hold_on: 20
    fade_hold_off: 10

  rainbow_10:
    rainbow_steps: 10
  rainbow_30:
    rainbow_steps: 30
  rainbow_250:
    rainbow_steps: 250

renderer:
  type: multi_all
  renderers:
    # Rainbows
    -
      type: rainbow
      section: top_left
      palette: rainbow_10
    -
      type: rainbow
      section: top_right
      palette: rainbow_30
    -
      type: rainbow
      section: bottom
      palette: rainbow_10

    # Patches
    -
      type: patch
      section: patch1
      palette: red
    -
      type: patch
      section: patch2
      palette: rainbow_250

    # Clock
    -
      type: clock
      section: bottom

    # Gravity shots
    -
      type: gravity_shot
      section: bottom

    # Gravity Drips
    -
      type: gravity_drip
      section: bottom

displays:
  -
    type: websocket
