controller:
  type: rectangular
  width: 12
  height: 120
  a: 5

displays:
  - type: websocket

sections:
  spokes:
    type: rectangular
    x: 0
    y: 0
    width: 12
    height: 120

renderer:
  type: multi_sequential
  common_parameters:
    section: spokes
  renderers:
    # LINES - DOWN
    -
      name: lines_down_red
      type: lines
      palette: red
      direction: down
    -
      name: lines_down_green
      type: lines
      palette: green
      direction: down
    -
      name: lines_down_blue
      type: lines
      palette: blue
      direction: down
    -
      name: lines_down_pink
      type: lines
      palette: pink
      direction: down
    -
      name: lines_down_white
      type: lines
      palette: white
      direction: down
    -
      name: lines_down_rainbow
      type: lines
      palette: rainbow_120
      direction: down

    # LINES - UP
    -
      name: lines_up_red
      type: lines
      palette: red
      direction: up
    -
      name: lines_up_green
      type: lines
      palette: green
      direction: up
    -
      name: lines_up_blue
      type: lines
      palette: blue
      direction: up
    -
      name: lines_up_pink
      type: lines
      palette: pink
      direction: up
    -
      name: lines_up_white
      type: lines
      palette: white
      direction: up
    -
      name: lines_up_rainbow
      type: lines
      palette: rainbow_120
      direction: up

    # SPARKLES
    -
      name: sparkles_red
      type: sparkles
      palette: red
    -
      name: sparkles_green
      type: sparkles
      palette: green
    -
      name: sparkles_blue
      type: sparkles
      palette: blue
    -
      name: sparkles_pink
      type: sparkles
      palette: pink
    -
      name: sparkles_white
      type: sparkles
      palette: white
    -
      name: sparkles_rainbow
      type: sparkles
      palette: rainbow_7

    # SPIRALS - FORWARD
    -
      name: spiral_forward_red
      type: spiral
      palette: red
      direction: /
      reverse: False
    -
      name: spiral_forward_green
      type: spiral
      palette: green
      direction: /
      reverse: False
    -
      name: spiral_forward_blue
      type: spiral
      palette: blue
      direction: /
      reverse: False
    -
      name: spiral_forward_pink
      type: spiral
      palette: pink
      direction: /
      reverse: False
    -
      name: spiral_forward_white
      type: spiral
      palette: white
      direction: /
      reverse: False
    -
      name: spiral_forward_rainbow_7
      type: spiral
      palette: rainbow_7
      direction: /
      reverse: False
    -
      name: spiral_forward_rainbow_120
      type: spiral
      palette: rainbow_120
      direction: /
      reverse: False

    # SPIRALS - FORWARD REVERSE
    -
      name: spiral_forward_reverse_red
      type: spiral
      palette: red
      direction: /
      reverse: True
    -
      name: spiral_forward_reverse_green
      type: spiral
      palette: green
      direction: /
      reverse: True
    -
      name: spiral_forward_reverse_blue
      type: spiral
      palette: blue
      direction: /
      reverse: True
    -
      name: spiral_forward_reverse_pink
      type: spiral
      palette: pink
      direction: /
      reverse: True
    -
      name: spiral_forward_reverse_white
      type: spiral
      palette: white
      direction: /
      reverse: True
    -
      name: spiral_forward_reverse_rainbow_7
      type: spiral
      palette: rainbow_7
      direction: /
      reverse: True
    -
      name: spiral_forward_reverse_rainbow_120
      type: spiral
      palette: rainbow_120
      direction: /
      reverse: True

    # SPIRALS - BACKWARD
    -
      name: spiral_backward_red
      type: spiral
      palette: red
      direction: \
      reverse: False
    -
      name: spiral_backward_green
      type: spiral
      palette: green
      direction: \
      reverse: False
    -
      name: spiral_backward_blue
      type: spiral
      palette: blue
      direction: \
      reverse: False
    -
      name: spiral_backward_pink
      type: spiral
      palette: pink
      direction: \
      reverse: False
    -
      name: spiral_backward_white
      type: spiral
      palette: white
      direction: \
      reverse: False
    -
      name: spiral_backward_rainbow_7
      type: spiral
      palette: rainbow_7
      direction: \
      reverse: False
    -
      name: spiral_backward_rainbow_120
      type: spiral
      palette: rainbow_120
      direction: \
      reverse: False

    # SPIRALS - BACKWARD REVERSE
    -
      name: spiral_backward_reverse_red
      type: spiral
      palette: red
      direction: \
      reverse: True
    -
      name: spiral_backward_reverse_green
      type: spiral
      palette: green
      direction: \
      reverse: True
    -
      name: spiral_backward_reverse_blue
      type: spiral
      palette: blue
      direction: \
      reverse: True
    -
      name: spiral_backward_reverse_pink
      type: spiral
      palette: pink
      direction: \
      reverse: True
    -
      name: spiral_backward_reverse_white
      type: spiral
      palette: white
      direction: \
      reverse: True
    -
      name: spiral_backward_reverse_rainbow_7
      type: spiral
      palette: rainbow_7
      direction: \
      reverse: True
    -
      name: spiral_backward_reverse_rainbow_120
      type: spiral
      palette: rainbow_120
      direction: \
      reverse: True
