#!/bin/bash
# /etc/init.d/rgbs

### BEGIN INIT INFO
# Provides:          rgbs
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage an RGBStrip
### END INIT INFO


case "$1" in
    start)
        echo "Starting rgbs"
        /home/pi/rgb_strip/init.d/rgbs_start.sh
        ;;
    stop)
        echo "Stopping rgbs"
        /home/pi/rgb_strip/init.d/rgbs_stop.sh
        ;;
    restart)
        echo "Restarting rgbs"
        /home/pi/rgb_strip/init.d/rgbs_stop.sh
        /home/pi/rgb_strip/init.d/rgbs_start.sh
        ;;
    *)
        echo "Usage: /etc/init.d/rgbs start|stop|restart"
        exit 1
        ;;
esac

exit 0
